README.md

This information is missing AFAIK which creates other trouble (people start using RSS feed to submit)

Added information about initial publishing

---

settings/class-instant-articles-option-analytics.php
settings/template-settings-info.php

There is a typo in the word WordPress. It should be WordPress and not Wordpress.

Wordpress -> WordPress

---

class-instant-articles-post.php
rules-configuration.json

Also fixes Interactive component to read the dimensions from source (included as a small nit in the PR for convenience).

Add new application header 

---

meta-box/meta-box-template.php

This will need to be added in order to be compatible with the new SDK

Checks if it have the node to be shown as warning body

---

meta-box/meta-box-template.php

This bit of copy shown in the info message of the Edit Post screen is more appropriate with the support for scheduled posts in PR https://github.com/Automattic/facebook-instant-articles-wp/pull/257

Copy updated to align better with scheduled posts

---

facebook-instant-articles.php

Allow filtering of the post types used in the feed

---

settings/class-instant-articles-option-ads.php

Removes extra newlines in select/optgroup tags

fix whitespace in select/optgroup tags

---

facebook-instant-articles.php
readme.txt

Releases #358 to fix an escaping bug

Release 3.0.1

---

rules-configuration.json

This PR:
Depends on release version of SDK: 1.3.1 (https://github.com/facebook/facebook-instant-articles-sdk-php)
Relates to https://github.com/facebook/facebook-instant-articles-sdk-php/pull/146

InteractiveInsideParagraphRule support and configuration

---

compat/jetpack-rules-configuration.json

Added rules for jetpack carousel component

---

facebook-instant-articles.php

Redirect settings

---

facebook-instant-articles.php
wizard/templates/app-setup-template.php
wizard/templates/style-selection-template.php
wizard/templates/wizard-template.php

This PR improves the text content of the UI flow.

Content update

---

class-instant-articles-publisher.php

Article with password protection

---

class-instant-articles-post.php

The `Instant_Articles_Post::get_cover_med`ia function was only partially completed and not yet implemented.
This caused issues for people trying to implement the `instant_articles_cover_media` filter.
I completed the function, and implemented it in Instant_Articles_Post::to_instant_article
* Fixes #398

Properly implemented the get_cover_media function.

---

readme.txt

Updates changelog and tested tag for latest code merges

Final release of v3.1

---

css/instant-articles-wizard.css

Relative CSS to fix missing icons

---

facebook-instant-articles.php
readme.txt

* Bumps the version number
* Adds v3.1.3 to the changelog

Release stuff for v3.1.3

---

rules-configuration.json

Added rule configuration for Instagram embed

---

rules-configuration.json

Fixes #408 adding rules for gallery

---

wizard/class-instant-articles-wizard.php

This PR fixes:
The flow redirects the user admin to reset and login again to revalidate and acquire new tokens.
Fixes #456 
Fixes #471

Token Invalidation flow

---

compat.php
compat/class-instant-articles-playbuzz.php
compat/playbuzz-rules-configuration.json

Support for Playbuzz plugin

---

rules-configuration.json

Fixes #205 - Caption in <p> tag

---

class-instant-articles-publisher.php
js/instant-articles-meta-box.js
meta-box/class-instant-articles-meta-box.php
meta-box/meta-box-template.php
wizard/class-instant-articles-option-publishing.php
wizard/class-instant-articles-wizard.php
wizard/templates/review-submission-template.php

Blocks publishing of articles with transformation warnings

---

facebook-instant-articles.php
readme.txt

Updates the versioning and adds a changelog for the v3.2 release

Release v3.2

---

meta-box/meta-box-template.php

This PR fixes the variable name causing all articles to be shown as filtered out by a rule (despite of being submitted anyway).

Fix variable name

---

compat.php
compat/class-instant-articles-playbuzz.php
tests/Facebook/InstantArticles/Transformer/WPTransformerTest.php
tests/Facebook/InstantArticles/Transformer/wp-ia.xml
tests/Facebook/InstantArticles/Transformer/wp-rules.json
tests/Facebook/InstantArticles/Transformer/wp.html

Fixes #515 - Enables Playbuzz plugin out of the box

---

composer.json

This way the plugin can be installed as dependency with composer.

Add missing information to composer.json

---

release.sh

This PR fixes a typo on the release script.

Fix typo on script

---

class-instant-articles-post.php
wizard/class-instant-articles-option-styles.php

* add an option to toggle RTL to advanced settings
* RTL will be applied for all articles once the option is enabled
fixes #317

capability to toggle RTL option

---

facebook-instant-articles.php

Adds ver=<VERSION_TOKEN> to invalidate plugin resource files

---

class-instant-articles-post.php

Add post ID to `instant_articles_content` filter

---

class-instant-articles-post.php
wizard/class-instant-articles-option-amp.php
wizard/templates/advanced-template.php

Fixes some undefined index warnings and also #703

Fixed several php notices. Also fixed a bug in should_subit_post()

---

release.sh

This PR ensures the changelog will be properly updated when releasing a new version.

Add changelog to script

---

compat.php
compat/class-instant-articles-comscore.php
compat/comscore.js
wizard/class-instant-articles-option-analytics.php

Add support for comScore analytics.

add Comscore plugin

---

facebook-instant-articles.php

avoid undefined index error in $display_warning_column

---

vipgo-helper.php

This PR:
Ensures plugins and localization are loaded in the VIP Go environment.
Relates to #391 #392.

Load functions which rely on `plugins_loaded` action hook in VIP Go environment

---

composer.lock

Updates composer.lock (with the results of `composer update`).

update composer modules

---

src/class-instant-articles-amp-markup.php
src/class-instant-articles-post.php
src/class-instant-articles-signer.php
src/compat.php
src/compat/apester-rules-configuration.json
src/compat/class-instant-articles-apester.php
src/compat/class-instant-articles-co-authors-plus.php
src/compat/class-instant-articles-comscore.php
src/compat/class-instant-articles-get-the-image.php
src/compat/class-instant-articles-google-analytics-for-wordpress.php
src/compat/class-instant-articles-gtm4wp.php
src/compat/class-instant-articles-jetpack.php
src/compat/class-instant-articles-playbuzz.php
src/compat/class-instant-articles-yoast-seo.php
src/compat/get-the-image-rules-configuration.json
src/compat/jetpack-rules-configuration.json
src/compat/playbuzz-rules-configuration.json
src/meta-box/class-instant-articles-meta-box.php
src/meta-box/meta-box-loader-template.php
src/meta-box/meta-box-template.php
src/wizard/class-instant-articles-option-ads.php
src/wizard/class-instant-articles-option-amp.php
src/wizard/class-instant-articles-option-analytics.php
src/wizard/class-instant-articles-option-fb-app.php
src/wizard/class-instant-articles-option-fb-page.php
src/wizard/class-instant-articles-option-publishing.php
src/wizard/class-instant-articles-option-styles.php
src/wizard/class-instant-articles-option.php
src/wizard/class-instant-articles-wizard.php

I ran some inspections in my IDE and collated a list of small maintenance fixes. See the individual commits for more details.

Various small maintenance fixes
