Automattic/fb-instant-articles

compat.php
compat/class-instant-articles-jetpack.php

Do not "fix" bare YouTube URLs on the own line as we have have oEmbed to handle those.
By unregistering the embed handler that Jetpack registers, we avoid the Jetpack YouTube HTML output altogether and let the oEmbed handler handle it.
Fixes #20

Jetpack compat: YouTube and Facebook embeds

---

class-instant-articles-post.php
template.php

Add support for subtitles through the filter instant_articles_subtitle

---

class-instant-articles-publisher.php
meta-box/class-instant-articles-meta-box.php
meta-box/meta-box-template.php

We decided to drop the feature where we submit drafts as drafts to Instant Articles. 
The feedback from community is that this behaviour is unexpected and that their libraries got polluted.

Stop publishing drafts

---

settings/template-settings-info.php

The link was actually empty. This PR adds the link with in a condition for when a Page ID has been defined.

Fixed empty link to Instant Articles signup

---

rules-configuration.json

This removes the rule:
```
{
"class": "CaptionRule",
"selector": "img",
"properties": {
"caption.default": {
"type": "string",
"selector": "img",
"attribute": "alt"
}
}
}
```
from `rules-configuration.json`. This rule forces all images to have captions, using the image's `alt` tag as the text. The is undesirable, as the alt text may not be what they user would want for the caption. By removing the rule, this prevents this behavior from occurring.
Fixes #153

Prevents <figcaptions> from being added to images that were not saved with captions

---

class-instant-articles-post.php

This PR is to avoid scheduled posts ending up as empty Instant Articles as per issue [#198](https://github.com/Automattic/facebook-instant-articles-wp/issues/198).
The removed check seems to be unnecessary, since a smarter check is done right after more gracefully.

Fix scheduled posts with empty IA content

---

meta-box/class-instant-articles-meta-box.php

The Facebook Open Graph scraper crawls the URL when trying to get the article ID by URL. In this case, we're avoiding to make this operation for unpublished URLs as it results in crawling a 404.
Fixes #237

Avoid crawler to cache a 404

---

class-instant-articles-post.php

Hyperlinks beginning with a # cause errors on Facebook ("Incorrect URL: Ensure all outbound URL links are valid.")

Remove hyperlinks beginning with a #

---

class-instant-articles-post.php
class-instant-articles-publisher.php
compat/class-instant-articles-jetpack.php
meta-box/meta-box-template.php
settings/class-instant-articles-option-ads.php
settings/class-instant-articles-option-publishing.php
settings/class-instant-articles-option.php
settings/class-instant-articles-settings-fb-page.php
settings/class-instant-articles-settings-wizard.php
settings/template-settings-advanced.php
settings/template-settings-info.php
settings/template-settings-wizard.php
wpcom-helper.php

This fixes spaces around parentheses, braces and other characters to conform to WordPress coding standards.
Fixes made automatically with `phpcbf`.

Fix whitespace to match WordPress coding standards

---

rules-configuration.json

SocialEmbeds were deprecated in favor of Interactive: https://developers.facebook.com/docs/instant-articles/reference/social

Replace SocialEmbed rules with Interactive rules

---

rules-configuration.json

This PR updates the default rules to use`interactive.width` and `interactive.height`.
Fixes #256, fixes #304.
Follows #342.
Follows facebook/facebook-instant-articles-sdk-php#100.

Width and Height for Interactive in default rules

---

class-instant-articles-post.php

This PR fixes the deprecated call to static DOMDocument::loadHTML() on line 644.
Follows #308.

Fixed statically-called loadHTML()

---

rules-configuration.json

This PR will prevent content within the `<mark>` tag from being stripped. Refer to issue: https://github.com/Automattic/facebook-instant-articles-wp/issues/240

Support <mark> tag

---

class-instant-articles-post.php

This fixes an issue when oembeds like instagram, twitter etc. use `<script async="" defer="defer" src="//platform.instagram.com/en_US/embeds.js"/>` instead of `<script async="" defer="defer" src="https://platform.instagram.com/en_US/embeds.js"/>`. Without this fix Facebook Instant Articles will report an error to the user about the article.

Fix relative URL issue with oembeds not using absolute URLs

---

settings/class-instant-articles-option-ads.php
settings/class-instant-articles-option-analytics.php
settings/class-instant-articles-option.php

This PR allows ampersands in the custom embed code for Ads and Analytics, e.g.:
```
<iframe src="http://foo.com?foo&amp;bar"></iframe>
```

Escape ampersands before displaying on settings page

---

settings/class-instant-articles-settings-fb-page.php

The plugin currently uses v2.5 of the Facebook API. This PR bumps it to v2.6, the current version.

use v2.6 of Facebook API

---

compat/class-instant-articles-jetpack.php

The Facebook SDK should always be loaded over HTTPS. We shouldn't use a protocol-relative URL.
Also bumped the SDK version to 2.6, which is current.

always use HTTPS to load JavaScript SDK; update to 2.6

---

class-instant-articles-publisher.php
meta-box/class-instant-articles-meta-box.php

This PR:
- Stores the submission ID of the posted article on post metadata.
- Uses the stored submission ID when available to fetch the article status instead of always getting it from the URL.
This fixes an issue where the meta-box does not show that the article was submitted unless you refresh the edit post screen, which feels broken.

Store and use submission ID when available to fetch the status

---

feed-template.php

Avoiding breaking `op-interactive` elements with iframes as per @gemedet's [comment](https://github.com/Automattic/facebook-instant-articles-wp/pull/331#discussion_r69826505).

Remove  to avoid breaking  elements. See #331

---

settings/class-instant-articles-option-ads.php
settings/class-instant-articles-option.php
wpcom-helper.php

This reverts commit 232b2c9c734856c4e590eb329fd139a2fd5e8b3f.
The escaping here is breaking the UI, as the variables being escaped here DO contain HTML, although it is not user-generated HTML, but hardcoded HTML configured on the descriptions provided for each field.

Revert "escaping and sanitization fixes"

---

class-instant-articles-post.php

This PR solves an issue with PHP throwing an `Notice:  Undefined index: host in /var/www/lin/wp-content/themes/vip/plugins/facebook-instant-articles-3.0/class-instant-articles-post.php on line 691`.

Ensure that relative URL checking has a host and a path.

---

rules-configuration.json

Improve rules for Images inside Paragraphs and Interactive elements

---

class-instant-articles-post.php

The plugin has functions built-in for subtitles; however it does not include it when constructing the header. Including it here allows users to use the built-in `instant_articles_subtitle` filter that allows users to target their subtitles, should they be part of their theme.
We’ve run into an issue during the submission process where subtitles where missing and Facebook mandating that we include them.

Add subtitle to $header when rendering post to IA

---

class-instant-articles-publisher.php

This PR:
Relates to Deprecation of field **take_live**
It was already renamed on the SDK, but was still lingering on the WordPress plugin.

Migrated take_live parameter to the published

---

compat/class-instant-articles-jetpack.php
compat/jetpack-rules-configuration.json

This PR:
Relates to https://github.com/facebook/facebook-instant-articles-sdk-php/pull/150
Fixes #333, #319, #289, #133

Jetpack plugin compatibility - Transformation rules

---

class-instant-articles-publisher.php
rules-configuration.json
settings/class-instant-articles-option-publishing.php

This PR:
Depends on SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/154

Commit blocker option - No warnings in transformer to publish

---

class-instant-articles-post.php

#This PR:
Fixes this issue #382 
Issue was intermittent and could be related to whether Instant Articles are under review on Facebook side (and thus disabling ability to delete Instant Articles on Facebook)
Fix suggested by @everton-rosario and worked for me.

Fix updating published posts result in error

---

class-instant-articles-post.php

Instead check whether wpautop is attached for 'the_content' and if it's not, add it. The reason for this is that we applied the_content filters already, and the shortcodes were rendered. Calling wpautop after shortcodes are rendered will mangle most of them, unless shortcode returns 1 line of code.

Don't call wpautop directly when trying to prepare content for transformation.

---

class-instant-articles-post.php

This PR hides warnings when using loadHTML, with a fix suggested by @everton-rosario.
Follows #383.

Fix loadHTML warning

---

class-instant-articles-post.php
rules-configuration.json

Apply "the_title" filter

---

facebook-instant-articles.php

Reverts Automattic/facebook-instant-articles-wp#389
While it's likely that a user will want to configure the plugin after activation, we shouldn't assume, and certainly shouldn't interrupt WP's normal behaviour.
A better approach would be a one-time post-activation admin message to point people to the settings page.

Revert "Redirect settings"

---

meta-box/class-instant-articles-meta-box.php

This PR removes a lingering reference to the old settings page removed on 3.1. This was breaking the meta-box.

Fix lingering reference to the old settings page on meta-box

---

wizard/class-instant-articles-option.php

This PR checks if the `double_encode` key exists before using it.
Fixes #404

Check for undefined index

---

compat.php
compat/class-instant-articles-get-the-image.php
compat/get-the-image-rules-configuration.json

Implemented compat for the get-the-image plugin

---

wizard/templates/wizard-template.php

Fixes #452 - Use of empty() on PHP prior to v5.5

---

wizard/class-instant-articles-wizard-state.php

This is blocking the wizard on integrations for sites where the root URL is overwritten by server rules.

Do not block page selection if URL is not claimed

---

css/instant-articles-meta-box.css
meta-box/class-instant-articles-meta-box.php
meta-box/meta-box-template.php

This PR:
Follows facebook/facebook-instant-articles-sdk-php#127

Add development mode support to status meta box

---

composer.json

This PR:
Relates to warning on build

Migration from old facebook sdk

---

class-instant-articles-post.php

As per [core documentation](https://codex.wordpress.org/Plugin_API/Filter_Reference/the_title), include the second argument to `the_title` as the current post ID.
Relates to #394

Apply the second argument to `the_title`

---

class-instant-articles-post.php
composer.json

This PR:
Follows #395
Relates to #369, #344
Fixes #339

Refactor to use transform string

---

meta-box/class-instant-articles-meta-box.php

Use the instant_articles_post_types filter when registering metaboxes

---

rules-configuration.json

This fixes the name of the getter to the correct one on the SDK.

Getter was renamed on SDK, updating here too

---

class-instant-articles-post.php

Fixes #447
Per the HTML5 spec, [if the src attribute is present on a script tag, the inner content must be empty](https://www.w3.org/TR/html5/scripting-1.html#the-script-element).
Setting all scripts to an absolute url using https protocol breaks script tags where the script is inline. (when a script tag This change checks to makes sure that the src attribute is not empty before updating it to an absolute url.

Only set https src on scripts that have a src attribute

---

class-instant-articles-publisher.php
feed-template.php

This PR:
adds `instant_articles_should_submit_post` filter hook to allow developers to control whether current post should be submitted to Instant Articles or not. 
The filter defaults to `TRUE` - the  post should be submitted to IA. We pass instance of Instant_Articles_Post to the filter.
Relates to #503 442 #275 #186
Fixes #503

Add instant_articles_should_submit_post filter hook  to allow developers control of whether the post should be submitted to IA

---

meta-box/class-instant-articles-meta-box.php
meta-box/meta-box-template.php

Show message on meta-box when post is filtered out

---

wpcom-helper.php

The WordPress.com stats pixel was being stripped out by the transformer. This change does several things;
* Adds the pixel via `instant_articles_after_transform_post`
* Uses the FBIA SDK to create FBIA-compatible markup for the stats pixel
* Adds the FBIA-compatible markup to the article
Tested on WordPress.com, but would appreciate a peer review and sanity check.

Update WordPress.com stats code to use FBIA SDK.

---

rules-configuration.json

Remove deprecated rules and add rules for imgs inside links

---

.gitignore
release.sh

Created a script to automatically:
Basic usage: ./release.sh -v <VERSION>

Add release script

---

class-instant-articles-publisher.php

This PR:
* Delay save_post action hook (3rd param 10 => 999) so that all custom meta data is processed and saved before submission to FBIA
Follows #
Relates to #487 
Fixes #

Change save_post priority

---

class-instant-articles-post.php
class-instant-articles-publisher.php
facebook-instant-articles.php

Adds a new function in the global namespace to check if the current view
being processed is for an instant article. Handles both the RSS feed and
content which is being processed for the Instant_Articles_Publisher
class. This conditional can be checked in any filters on 'the_content',
'the_title' or elsewhere that need to treat Instant Articles content
separately from web content.
See #426

Add `is_transforming_instant_article()` conditional

---

compat/class-instant-articles-jetpack.php
embeds.php

This PR is built on top of #457 and using the solution introduced by #568.
It prevents the compat layer from messing with the regular FE output, running only during the Instant Article transformation.

Don't try to load embeds compat unless we're in Instant Articles context

---

compat/class-instant-articles-jetpack.php

See #337 
Here's a different approach to #401 PR for that ticket,  this is just for fb embeds, I haven't tested it for the rest of the layers. 
The idea here is that 'instant_articles_before_transform' post runs only for IA context, so we can relatively safely attach our stuff here and it won't affect the rest of contexts.
Small extra - `op-social` was deprecated awhile back, so I replaced that with `op-interactive`

Don't try to load FB embeds compat unless we're in Instant Articles context

---

rules-configuration.json

This PR:
Adds a transformer rule for the cite element adding the ItalicRule class.

Add transformer rule for cite element

---

embeds.php

This PR:
Fixes #
few typos with variable spelling causing the added fix for Vimeo, Facebook and Vine not working.

Fix typo for $provider_url at L42, L44 and L46

---

class-instant-articles-publisher.php

This adds a `instant_articles_post_published` hook to allow a plugin to change the `published` field on newly saved posts.

Call instant_articles_post_published hook to determine published status

---

class-instant-articles-post.php
wizard/class-instant-articles-option-styles.php

Add an option to set a footer

---

class-instant-articles-post.php
wizard/class-instant-articles-option-publishing.php

Relates to https://github.com/facebook/facebook-instant-articles-sdk-php/pull/195
Replaces #605 
Fixes #36 and #340

Switch on/off configuration for enabling comments/likes by default

---

compat.php
compat/apester-rules-configuration.json
compat/class-instant-articles-apester.php

Apester plugin support

---

facebook-instant-articles.php

Extracted anonymous inline function

---

class-instant-articles-post.php

as @yssk22 commented in #428, the refactored code has been reverted back by mistake, and it result in garbled MB characters in title.
This PR:
Relates to #428

fix merge damage

---

class-instant-articles-post.php

Added ability to set own file path for the rules-configuration.json file so that developers can specify their own json rules and not run the risk of updates to this plugin effecting the way their transformed instant articles behave.
This PR:

Allow for alternative file path for json rules

---

class-instant-articles-publisher.php

This PR:
Fixes #
For wp_is_post_autosave() to works, it requires $post->ID and not just $post object.
Reference: https://codex.wordpress.org/Function_Reference/wp_is_post_autosave

Fix wp_is_post_autosave() parameter value

---

compat.php
compat/class-instant-articles-google-analytics-for-wordpress.php

Update Google Analytics compat

---

class-instant-articles-post.php
rules-configuration.json
wizard/class-instant-articles-option-styles.php

This PR:
- adds capability to markups in footer
- closes #619
- depends on facebook/facebook-instant-articles-sdk-php/pull/198

allow markups in footer/copyright

---

.gitignore
class-instant-articles-amp-markup.php
composer.json
composer.lock
facebook-instant-articles.php
wizard/class-instant-articles-option-amp.php
wizard/class-instant-articles-option-fb-page.php
wizard/class-instant-articles-option-publishing.php
wizard/class-instant-articles-wizard.php
wizard/templates/advanced-template.php

This PR is to enable the IA->AMP conversion from articles. It includes the newly released extensions SDK.

Adding support to IA->AMP conversion

---

class-instant-articles-post.php

This PR:
Fixes #
Fix `PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input`, by verifying the content and making sure if it is empty, do not `transformString`.
Automattic/facebook-instant-articles-wp#628

Fix "Empty string supplied as input" bug

---

wizard/class-instant-articles-option-amp.php

Enables you to delete a previous set JSON Style
Add the default index to Instant_Articles_AMP_Markup::SETTING_STYLE array.

Enable deletion of JSON AMP Style and removes an undef index

---

meta-box/class-instant-articles-meta-box.php

Fixes a NOTICE that is being shown before the headers.

Check for array index before using it

---

class-instant-articles-post.php
facebook-instant-articles.php

This PR address the 10% performance regression reported on the WordPress plugin support forum. 
I'm adding a cache layer using a simple post meta to avoid transforming the article to Instant Article at every page render for calculating whether it's a valid IA (which we use to decide whether to include the ia-markup meta tag or not).

Add cache layer for avoiding transforming the article at page render

---

facebook-instant-articles.php

This PR prevents the plugin from trying to inject the meta-tag on non-post pages, which was causing NOTICES to be shown on the debug log.
Fixes #707

Do not process non-post pages. Fixes #707

---

wpcom-helper.php

Fixes an issue introduced in #724 and 4a51b4c03bafb76a0ffb48cfce1f8a578bbdbf67
This PR:
Relates to #525
Fixes #724

Restore the $current_blog global and fix the post ID reference

---

class-instant-articles-amp-markup.php

This PR addresses the issues found on the VIP review:

Fix query limit and escaping on AMP generation

---

embeds.php

For each oEmbed on a page, an uncached remote request is made to check the oEmbed provider's URL.  This patch adds a level of caching to stop from having to check each oEmbed on every page load.
It's unlikely that an oEmbed provider will change for a specific URL, so there shouldn't be any need to specify an expiration on the good cached data.
This PR:
Fixes #685

Adds caching to instant_articles_embed_oembed_html

---

meta-box/class-instant-articles-meta-box.php
meta-box/meta-box-error.php

This PR:
See #770 for initial problem. This PR adds a generic error message that is displayed if the meta box can't be loaded.
fixes #770

Display error message if meta box can't be loaded

---

README.md
meta-box/meta-box-template.php

Due to the [recent change](https://developers.facebook.com/blog/post/2017/07/18/graph-api-v2.10) in the Graph API articles are not being published to Facebook automatically anymore but rather have to be shared first. See also #791 
This updates all messaging to account for this change.

Change meta box and readme so user doesn't think IAs are actually submitted to Facebook

---

LABELS.md

This PR:
Adds a file which describes the meaning of the labels that we use so we can
* Consistently use the labels
* Help our users understand why their issue was tagged with certain labels

Add label definitions

---

composer.json
facebook-instant-articles.php
meta-box/class-instant-articles-meta-box.php

This PR:
Removes the code that triggers a rescrape for an article. Due to a recent change in the Graph API this code does not work anymore.

remove article rescrape code

---

README.md

This PR adds some clarification to the README file about the requirement of having your domain connected for your articles to show up under Publishing Tools.

Clarify requirement of site connection in README

---

rules-configuration.json
tests/Facebook/InstantArticles/Transformer/wp-ia.xml
tests/Facebook/InstantArticles/Transformer/wp-rules.json
tests/Facebook/InstantArticles/Transformer/wp.html

This PR adds a default rule to transform Twitter Embed codes (those copied from the Twitter website.) This rule is parallel to the existing one we have for Instagram.
Fixes #669

Add default rule for Twitter blockquote

---

class-instant-articles-post.php

This PR fixes #864 
It now correctly applies the filter style

[bugfix] calling get_article_style to apply the style filter

---

wizard/class-instant-articles-option-amp.php

(wizard) Update wording about AMP markup gen

---

compat/playbuzz-rules-configuration.json

This extra rule support Playbuzz plugin next version,
Playbuzz plugin next version support new Playbuzz embed code v3.0, for match better SEO and removes deprecated Playbuzz code dependencies
This PR: adding the ability to use the new Playbuzz plugin which use the new Playbuzz embed code, 
It won't break the support of the old Playbuzz embed code (v2).
Relates to #895

feat(playbuzz): support for the next major playbuzz plugin version

---

composer.json
composer.lock
facebook-instant-articles.php
wizard/class-instant-articles-option-fb-app.php
wizard/class-instant-articles-wizard.php
wizard/templates/advanced-template.php

Enables setup for updating/invalidating articles cache from Facebook scraper

---

compat.php
compat/class-instant-articles-gtm4wp.php

Add support for GTM4WP

---

rules-configuration.json

This PR:
Whenever Grammarly makes a correction in text, it wraps the text with `<g>` tags like this:
```html
<g class="gr_ gr_8 gr-alert gr_gramm gr_inline_cards gr_run_anim Grammar only-ins replaceWithoutSep" id="8" data-gr-id="8">Because</g>
```
This PR adds a PassThroughRule for the `g` selector.
See also: https://github.com/tinymce/tinymce/issues/3625#issuecomment-299881345

Add PassThroughRule for Grammarly

---

README.md

Making the requirements for using Instant Articles (a prerequisite for the WP plugin) a little clearer

Updating description for the plugin

---

class-instant-articles-signer.php
facebook-instant-articles.php

This PR aims to do trigger a token-less re-scrape of the URLs being updated to trigger a new Instant Article ingestion even if the user does not have a configured app ID/app secret/access token.

Add token-less re-scrape with request signature

---

embeds.php

This PR:
Delete transient when create on autoload=yes, which is overloading the mysql response, which needs to return a huge amount of completely unnecessary information.
Follows #
Relates to # Issue: https://github.com/Automattic/facebook-instant-articles-wp/issues/901#issuecomment-396352556
Fixes # Delete transient when create on autoload=yes

Delete current transient with autoload=yes.

---

class-instant-articles-post.php
composer.json
composer.lock
facebook-instant-articles.php
tests/Facebook/InstantArticles/Transformer/WPTransformerTest.php
wizard/class-instant-articles-option-publishing.php

This adapts the Instant Articles Wordpress plugin to adapt to the deprecation of media feedback to individual media components of Instant Articles.
Commonly used attribute into the figure.
```
<figure data-feedback="fb:likes, fb:comments">
</figure>
```
This takes no effect and we stopped outputting in case this gets enabled. So the methods enabling/disabling data-feedback are set to do nothing now. 
On the plugin, we removed the setup page for this properties.
Relates to https://github.com/facebook/facebook-instant-articles-sdk-php/pull/347

Removed fields from deprecated feature to enable comments/likes/share from media content

---

composer.json

Update Facebook Instant Articles SDK to 1.10.0 (from 1.9.0) and Facebook Instant Articles Extensions SDK to 0.2.1 (from 0.1.0).

Update Facebook SDK versions

---

class-instant-articles-post.php

Allow post content caching to be disabled

---

class-instant-articles-post.php

Fixes a bug which results in a fatal error due to a missing argument passed to the `get_the_excerpt` filter hook.
Fixes https://github.com/Automattic/facebook-instant-articles-wp/issues/1063.

fix: pass the missing $post param to the get_the_excerpt filter

---

.github/workflows/stale.yml

This pull request introduces a GitHub workflow that runs daily and will automatically mark inactive issues and PRs as stale. Keeping issues and pull requests manageable and actionable is important for a codebase's health.
The default behavior of this action will mark issues and pull requests as stale after **60 days** of inactivity, by adding a label of `[Status] Stale` and leaving an explanatory comment ([example](https://github.com/Automattic/eslint-config-wpvip/issues/6#issuecomment-1215909749)). This PR uses 30 days for this repository though, as there are a lot of outstanding issues. If another **7 days** of inactivity pass, it will be labeled `[Status] Autoclosed` and closed. (It can always be reopened, which resets the clock.)
This action ignores issues and PRs with the following …

Add GitHub workflow to mark issues and PR as stale

---

facebook-instant-articles.php

Right now when adding this plugin via wpackagist (or in my case a fork published to packagist) it fatals because it expects the plugin to be built. This checks if the FB classes are already available.

Support for installing as composer package

---

embeds.php

Cached or not, the result of the remote request is only used to determine if
`instant_articles_embed_get_html()` should be called, which itself returns
early when called outside of the transformation process. If a post is never
published to Instant Articles, neither the remote request nor its cached result
are necessary; due to the filter this is hooked to, it will be called regardless.
On a high-traffic site, or a site without a persistent object cache and limited
MySQL resources, rendering a post that contains many embeds can exhaust
resources or eject from cache data that is of greater benefit to remain in cache.
Follows #775
Relates to #252, #1067, #901

Reduce plugin's cache burden, remote requests

---

class-instant-articles-post.php

Hiya!
It would be more ideal to allow for the default behavior to execute and then, users can add the filter to overwrite `$cover_media` if they wish to do so.
props @sboisvert

Fix the way filters are applied in `get_cover_media`

---

.github/workflows/tests.yml

All of the dependencies can now run on PHP 8.2, so no need to ignore platform requirements.

Actions: Remove separate PHP 8.2 composer install

---

class-instant-articles-post.php
tests/Facebook/InstantArticles/Transformer/WPTransformerTest.php
tests/InstantArticlesPostTest.php

- Use self::factory() method instead of deprecated $this->factory property. See https://core.trac.wordpress.org/changeset/54087
- Use more accurate assertions (Equals -> Same, Equals -> Count, Equals -> IsString/IsArray, etc.)
- Add a property to stop it being dynamic.
- Declare strict_types=1 in test files.
- Rename test methods to camel case.

Improve tests

---

wizard/class-instant-articles-option-fb-app.php
wizard/class-instant-articles-option-fb-page.php

Makes the constructor of these two option classes match the others.
Fixes #683.

Fix wizard option dynamic properties for PHP 8.2

---

facebook-instant-articles.php

In certain circumstances, the `post_updated` hook may be called twice, so the parent callback function that held the nested functions would run twice, trying to define an already defined function.
Fixes #981.

Un-nest admin notices callback functions

---

src/wizard/class-instant-articles-option.php

Missing params are a fatal error with PHP 7.1. In this case, the universal renderer was not being called with any disable configuration on a field, so it wasn't at risk.
Fixes #874.

Fix calls to disable() with missing params
